spring.config.activate.on-profile=k8s
spring.datasource.url=jdbc:mysql://${URL_HOST_MYSQL}:${URL_PORT_MYSQL}/${DB_MYSQL}?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.kafka.bootstrap-servers=${URL_HOST_KAFKA}:${URL_PORT_KAFKA}
spring.jpa.properties.hibernate.cache.redisson.config = redisson/redisson_k8s.yml
