FROM jenkins/inbound-agent
USER root
RUN usermod -g root jenkins
RUN curl -L "https://github.com/docker/compose/releases/download/v2.39.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
#RUN --mount=type=bind,target=/var/run/docker.sock,source=/var/run/docker.sock
USER jenkins