flyway.user=root
flyway.password=root
flyway.schemas=kafka_db
flyway.url=jdbc:mysql://host.docker.internal:3306
flyway.baselineOnMigrate= true
flyway.baselineVersion=0
flyway.locations=filesystem:flyway/scripts/